# One-time HIVE SSH bootstrap for a Windows machine PC.
# Run locally as Administrator, using the public key generated by HIVE Central.

param(
    [Parameter(Mandatory = $true)]
    [string]$PublicKeyPath
)

$ErrorActionPreference = "Stop"

function Require-Admin {
    $Identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $Principal = New-Object Security.Principal.WindowsPrincipal($Identity)
    if (-not $Principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Run this bootstrap from an Administrator PowerShell window."
    }
}

Require-Admin
if (-not (Test-Path -LiteralPath $PublicKeyPath)) {
    throw "HIVE public key not found: $PublicKeyPath"
}
$PublicKey = (Get-Content -LiteralPath $PublicKeyPath -Raw).Trim()
if ($PublicKey -notmatch '^(ssh-ed25519|ecdsa-sha2-nistp256|ssh-rsa)\s+[A-Za-z0-9+/=]+(?:\s+.*)?$') {
    throw "The selected file is not a supported OpenSSH public key."
}

$Capability = Get-WindowsCapability -Online | Where-Object Name -Like 'OpenSSH.Server*' | Select-Object -First 1
if (-not $Capability) { throw "This Windows version does not expose the OpenSSH Server capability." }
if ($Capability.State -ne 'Installed') {
    Write-Host "Installing Windows OpenSSH Server..."
    Add-WindowsCapability -Online -Name $Capability.Name | Out-Null
}

Set-Service -Name sshd -StartupType Automatic
Start-Service sshd

$SshDir = Join-Path $env:ProgramData "ssh"
$AuthorizedKeys = Join-Path $SshDir "administrators_authorized_keys"
New-Item -ItemType Directory -Force -Path $SshDir | Out-Null
$Existing = if (Test-Path -LiteralPath $AuthorizedKeys) {
    @(Get-Content -LiteralPath $AuthorizedKeys | ForEach-Object { $_.Trim() } | Where-Object { $_ })
} else { @() }
if ($PublicKey -notin $Existing) {
    Add-Content -LiteralPath $AuthorizedKeys -Value $PublicKey -Encoding ASCII
}
& icacls.exe $AuthorizedKeys /inheritance:r /grant:r "*S-1-5-18:F" "*S-1-5-32-544:F" | Out-Null

$ConfigPath = Join-Path $SshDir "sshd_config"
if (Test-Path -LiteralPath $ConfigPath) {
    $Config = Get-Content -LiteralPath $ConfigPath -Raw
    if ($Config -match '(?m)^\s*#?\s*PubkeyAuthentication\s+') {
        $Config = $Config -replace '(?m)^\s*#?\s*PubkeyAuthentication\s+.*$', 'PubkeyAuthentication yes'
    } else {
        $Config += "`r`nPubkeyAuthentication yes`r`n"
    }
    Set-Content -LiteralPath $ConfigPath -Value $Config -Encoding ASCII
}

$DefaultRule = Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue
if ($DefaultRule) {
    Set-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -Enabled True -Profile Any -RemoteAddress LocalSubnet | Out-Null
} else {
    New-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -DisplayName "OpenSSH Server (HIVE local subnet)" `
        -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 `
        -RemoteAddress LocalSubnet | Out-Null
}
Restart-Service sshd

Write-Host ""
Write-Host "HIVE SSH bootstrap complete on $env:COMPUTERNAME." -ForegroundColor Green
Write-Host "SSH is limited to the local subnet and accepts the HIVE public key."
Write-Host "Compare one of these fingerprints with the HIVE Setup screen before approving trust:" -ForegroundColor Yellow
Get-ChildItem -LiteralPath $SshDir -Filter "ssh_host_*_key.pub" | ForEach-Object {
    & ssh-keygen.exe -lf $_.FullName
}
Write-Host ""
Write-Host "Use an existing local Administrator username when HIVE asks for the SSH user."
